#   Target
PROGRAM_spu := lab9_spu
LIBRARY_embed := lib_lab9_spu.a

# include partea care face toata treaba pe baza definitiilor de mai sus

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
